config/routes.rb
BlogExercise::Application.routes.draw do
  
  get "home/index"
  get 'admin' => 'admin/blogs#index'
  get 'blog/:id' => 'home#blog'

  namespace :admin do
    resources :blogs
  end
  resources :comments

  root 'home#index'

  

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/blog.rb
class Admin::Blog < ActiveRecord::Base
	validates :title, :body, presence: true
	validates :title, uniqueness: true
	validates :body, length: { minimum: 100 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
  scope :comments_for_blog, lambda { |id|
    where(blog_id: id)
  }
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < ApplicationController
  before_action :set_admin_blog, only: [:show, :edit, :update, :destroy]
  layout 'admin'
  # GET /admin/blogs
  # GET /admin/blogs.json
  def index
    @blogs = BlogList.new.get_list
  end

  # GET /admin/blogs/1
  # GET /admin/blogs/1.json
  def show
  end

  # GET /admin/blogs/new
  def new
    @blog = CreateBlog.new_blog
  end

  # GET /admin/blogs/1/edit
  def edit
  end

  # POST /admin/blogs
  # POST /admin/blogs.json
  def create
    respond_to do |format|
      if CreateBlog.publish_new_blog(admin_blog_params)
        format.html { respond_on_success('create') }
      else
        @blog = CreateBlog.blog
        format.html { render action: 'new' }        
      end
    end
  end

  def respond_on_success(action)
     redirect_to admin_blogs_path, notice: "Blog was successfully #{action}d."    
  end

  # PATCH/PUT /admin/blogs/1
  # PATCH/PUT /admin/blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(admin_blog_params)
        format.html { respond_on_success('update') }
      else        
        format.html { render action: 'edit' }        
      end
    end
  end

  # DELETE /admin/blogs/1
  # DELETE /admin/blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to admin_blogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_blog
      @blog = Admin::Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_blog_params
      params.require(:admin_blog).permit(:title, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def create
  	@success = BlogComment.comment_on_blog(comments_params)
  	respond_to do |format|
  		format.js
  	end
  end

  private
   
    # Never trust parameters from the scary internet, only allow the white list through.
    def comments_params
      params.require(:comment).permit(:text, :commented_by_name, :commented_by_email, :blog_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'application'
  def index
  	@blogs = BlogList.new.get_list
  end

  def blog
  	@blog = Admin::Blog.find(params[:id])
  	@comments = Comment.comments_for_blog(@blog.id)
  end

end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def formatted_date(datetime)
		datetime.strftime('%B %d, %Y')
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@blog.errors.count, "error") %> prohibited this admin_blog from being saved:</h4>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control ckeditor"  %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/blogs/edit.html.erb
 <ol class="breadcrumb">
  <li>
      <i class="fa fa-dashboard"></i>  <a href="<%= admin_blogs_path %>">Blogs</a>
  </li>
  <li class="active">
      <i class="fa fa-table"></i> Edit
  </li>
</ol>
<%= render 'form' %>

app/views/admin/blogs/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div>
      <%= link_to '<button class="btn btn-success btn-small pull-right">+ New Blog</button>'.html_safe, 
        new_admin_blog_path, data: { no_turbolink: true } %>
    </div>    
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Title</th>
            <th>Body</th>
            <th>Actions</th>                    
          </tr>
        </thead>
        <tbody>
          <% @blogs.each do |admin_blog| %>
            <tr>
              <td><%= link_to admin_blog.title, admin_blog %></td>
              <td><%= admin_blog.body.truncate(100) %></td>
              <td>
                <%= link_to 'Edit', edit_admin_blog_path(admin_blog), 
                  data: { no_turbolink: true } %> | 
                <%= link_to 'Destroy', admin_blog, method: :delete, 
                  data: { confirm: 'Are you sure?' } %>             
              </td>                    
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/blogs/new.html.erb
 <ol class="breadcrumb">
  <li>
      <i class="fa fa-dashboard"></i>  <a href="<%= admin_blogs_path %>">Blogs</a>
  </li>
  <li class="active">
      <i class="fa fa-table"></i> New
  </li>
</ol>
<%= render 'form' %>

app/views/admin/blogs/show.html.erb
<ol class="breadcrumb">
  <li>
      <i class="fa fa-dashboard"></i>  <a href="<%= admin_blogs_path %>">Blogs</a>
  </li>
  <li class="active">
      <i class="fa fa-table"></i> <%= @blog.title.truncate(100) %>
  </li>
</ol>
<div class="col-lg-12">
  <h2 class="page-header"><%= @blog.title %></h2>
  <p class="lead"><%= @blog.body.html_safe %></p>
</div>

app/views/comments/create.js.erb
<% if @success %>
	window.reload();
<% else %>
	alert("Please fill correct information.");
<% end %>

app/views/home/_comment_form.html.erb
<%= form_for Comment.new, method: :post, remote: true do |f| %>
	<%= f.text_field :commented_by_name, placeholder: 'Your Name' %></br>
	<%= f.text_field :commented_by_email, placeholder: 'Your Email' %></br>
	<%= f.text_area :text, placeholder: 'Type comment here' %></br>
	<%= f.hidden_field :blog_id, value: blog_id %>
	<%= f.submit 'Comment'%>
<% end %>

app/views/home/add_comment.js.erb
<% if @success %>
	window.location.reload();
<% else %>
	alert("Please fill correct information.");
<% end %>

app/views/home/blog.html.erb
<div class="col-lg-12">
  <h2 class="page-header"><%= @blog.title %></h2>
  <p class="lead"><%= @blog.body.html_safe %></p>
</div>
<div class="col-lg-12">
	<div class="row">Comments:</div>
	<% @comments.each do |c| %>
		<blockquote><%= c.text %></blockquote> - <%= c.commented_by_name %>
	<% end %>
	<div class="row">
		<div id="comment_form_container">
			<%= render partial: 'comment_form', locals: { blog_id: @blog.id } %>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <% @blogs.each do |blog| %>
      <div class="post-preview">
          <a href="<%= '/blog/'+blog.id.to_s %>">
            <h2 class="post-title">
              <%= blog.title %>
            </h2>              
          </a>
          <p class="post-meta">Posted by 
            <a href="#">Simple Blog</a> on <%= formatted_date(blog.created_at) %>
          </p>
      </div>
      <hr>
    <% end %>      
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple Blog</title>
  <%= stylesheet_link_tag    "admin", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "admin", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div id="wrapper">
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="/">SB Admin</a>
      </div>
      
      <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav side-nav">              
              <li class="active">
                  <a href="<%= admin_blogs_path %>"><i class="fa fa-fw fa-table"></i> Blogs</a>
              </li>                    
          </ul>
      </div>
      <!-- /.navbar-collapse -->
  	</nav>

  	<div id="page-wrapper">
      <div class="container-fluid">
        <%= yield %>
      </div>	
    </div>  	
	</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogExercise</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Simple Blog</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/">Home</a>
                    </li>
                    <li>
                        <a href="/">About</a>
                    </li>
                    <li>
                        <a href="/">Sample Post</a>
                    </li>
                    <li>
                        <a href="/">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->        
    	</nav>

    	<header class="intro-header">
			  <div class="container">
			    <div class="row">
			      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
			        <div class="site-heading">
			          <h1>Simple Blog</h1>
			          <hr class="small">
			          <span class="subheading">Start blogging with Simple Blog.</span>
			        </div>
			      </div>
			    </div>
			  </div>
			</header>

			<div class="container">
				<%= yield %>
			</div>
			<hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>